name: chat_buddy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.6
  flutter_launcher_icons: ^0.9.2
  local_auth: ^1.1.10
  fluttertoast: ^8.0.8
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.2.0
  firebase_auth: ^3.3.5
  form_field_validator: ^1.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  image_picker: ^0.8.4+4
  path:
  curved_navigation_bar: ^1.0.1
  provider: ^6.0.2
  custom_full_image_screen: ^0.0.4
  cached_network_image: ^3.2.0
  flutter_local_notifications: ^9.3.1
  rxdart: ^0.27.3
  firebase_messaging: ^11.2.6
  shimmer: ^2.0.0
  lottie: ^1.2.1
  assets_audio_player: ^3.0.4+1
  permission_handler: ^8.3.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/chat_logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/audio/

